### ISSUE TITLE
Windows build fails on npm link

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#168]
#### Issue Description

The ecosystem tests fail on `npm link` in windows. I don't know why.

```
>> 4. linking the local trails build into dependencies...
events.js:160
      throw er; // Unhandled 'error' event
      ^
 
Error: spawn npm ENOENT
    at exports._errnoException (util.js:896:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

#### Environment
- node version: all
- trails version: all
- operating system: Windows (appveyor)

**Comment by tjwebb** [comment]
I bet it's this, due to the forward slash: https://github.com/trailsjs/smokesignals/blob/master/lib/ecosystem.js#L80
