### ISSUE TITLE
Fresh project crash

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#173]
#### Issue Description
Now under `config/database.js` the store is commented. And all database dependencies have been removed. If users follow the tutorial they now have an error. 

```
Initialized empty Git repository in C:/trails/tutoTrails/.git/

C:\trails\tutoTrails>npm start

> tuto-trails@0.0.0 start C:\trails\tutoTrails
> node server.js

debug: The config setting i18n.resources is defined by both trailpack-core and the application. trailpack-core:i18n.resources will be merge with application settings.
debug: The config setting resources.en is defined by both trailpack-core and the application. trailpack-core:resources.en will be merge with application settings.
debug: trails event: trailpack:core:constructed
debug: trails event: trailpack:repl:constructed
debug: trails event: trailpack:router:constructed
debug: trails event: trailpack:hapi:constructed
debug: trails event: trailpack:waterline:constructed
debug: The config setting footprints.controllers is defined by both trailpack-footprints and the application. The controllers config defined in trailpack-footprints will be ignored.
debug: The config setting footprints.models is defined by both trailpack-footprints and the application. The models config defined in trailpack-footprints will be ignored.
debug: The config setting footprints.prefix is defined by both trailpack-footprints and the application. The prefix config defined in trailpack-footprints will be ignored.
debug: The config setting controllers.method is defined by both trailpack-footprints and the application. The method config defined in trailpack-footprints will be ignored.
debug: The config setting controllers.ignore is defined by both trailpack-footprints and the application. The ignore config defined in trailpack-footprints will be ignored.
debug: The config setting models.options is defined by both trailpack-footprints and the application. The options config defined in trailpack-footprints will be ignored.
debug: The config setting models.actions is defined by both trailpack-footprints and the application. The actions config defined in trailpack-footprints will be ignored.
debug: The config setting options.defaultLimit is defined by both trailpack-footprints and the application. The defaultLimit config defined in trailpack-footprints will be ignored.
debug: The config setting options.populate is defined by both trailpack-footprints and the application. The populate config defined in trailpack-footprints will be ignored.
debug: The config setting actions.create is defined by both trailpack-footprints and the application. The create config defined in trailpack-footprints will be ignored.
debug: The config setting actions.find is defined by both trailpack-footprints and the application. The find config defined in trailpack-footprints will be ignored.
debug: The config setting actions.update is defined by both trailpack-footprints and the application. The update config defined in trailpack-footprints will be ignored.
debug: The config setting actions.destroy is defined by both trailpack-footprints and the application. The destroy config defined in trailpack-footprints will be ignored.
debug: The config setting actions.createAssociation is defined by both trailpack-footprints and the application. The createAssociation config defined in trailpack-footprints will be ignored.
debug: The config setting actions.findAssociation is defined by both trailpack-footprints and the application. The findAssociation config defined in trailpack-footprints will be ignored.
debug: The config setting actions.updateAssociation is defined by both trailpack-footprints and the application. The updateAssociation config defined in trailpack-footprints will be ignored.
debug: The config setting actions.destroyAssociation is defined by both trailpack-footprints and the application. The destroyAssociation config defined in trailpack-footprints will be ignored.
debug: trails event: trailpack:footprints:constructed
debug: trails event: trails:start
debug: trails event: trailpack:footprints:validated
debug: trails event: trailpack:repl:validated
debug: trails event: trailpack:core:validated
debug: trails event: trailpack:hapi:validated
debug: trails event: trailpack:waterline:validated
debug: trails event: trailpack:router:validated
debug: trails event: trailpack:all:validated
debug: historyFile C:\trails\tutoTrails\.tmp\.node_repl_history
debug: trails event: trailpack:repl:configured
debug: trails event: trailpack:hapi:configured
debug: trails event: trailpack:waterline:configured
debug: trails event: trailpack:router:configured
debug: trails event: trailpack:core:configured
debug: trails event: trailpack:footprints:configured
debug: trails event: trailpack:all:configured
debug: trails event: i18n:ready
debug: trails event: trailpack:repl:initialized
debug: trails event: trailpack:router:initialized
debug: trails event: trailpack:footprints:initialized
debug: trails event: trailpack:core:initialized
debug: trailpack-hapi: registering 2 plugins
error:
 Error: The connection dev specified in user does not exist!
    at C:\trails\tutoTrails\node_modules\waterline\lib\waterline\collection\loader.js:101:13
    at Array.forEach (native)
    at _getConnections (C:\trails\tutoTrails\node_modules\waterline\lib\waterline\collection\loader.js:96:35)
    at new module.exports (C:\trails\tutoTrails\node_modules\waterline\lib\waterline\collection\loader.js:23:32)
    at loadCollection (C:\trails\tutoTrails\node_modules\waterline\lib\waterline.js:111:18)
    at C:\trails\tutoTrails\node_modules\waterline\node_modules\async\lib\async.js:162:20
    at C:\trails\tutoTrails\node_modules\waterline\node_modules\async\lib\async.js:230:13
    at _arrayEach (C:\trails\tutoTrails\node_modules\waterline\node_modules\async\lib\async.js:81:9)
    at _each (C:\trails\tutoTrails\node_modules\waterline\node_modules\async\lib\async.js:72:13)
    at Object.async.forEachOf.async.eachOf (C:\trails\tutoTrails\node_modules\waterline\node_modules\async\lib\async.js:229:9)
    at Object.async.forEach.async.each (C:\trails\tutoTrails\node_modules\waterline\node_modules\async\lib\async.js:206:22)
    at Array.async.auto.loadCollections (C:\trails\tutoTrails\node_modules\waterline\lib\waterline.js:125:13)
    at C:\trails\tutoTrails\node_modules\waterline\node_modules\async\lib\async.js:590:38
    at _arrayEach (C:\trails\tutoTrails\node_modules\waterline\node_modules\async\lib\async.js:81:9)
    at Object.async.auto (C:\trails\tutoTrails\node_modules\waterline\node_modules\async\lib\async.js:552:9)
    at Waterline.initialize (C:\trails\tutoTrails\node_modules\waterline\lib\waterline.js:121:9)
error: The application did not boot successfully.
error: Try increasing the loglevel to "debug" to learn more
debug: trails event: trails:stop
info: Shutting down...
debug: Unloading trailpack core
debug: Unloading trailpack repl
debug: config.paths.www: No www directory is set, static files will not be loaded
debug: config.views: No view engine is set. Not loading.
debug: trails event: trailpack:hapi:initialized
``` 

The generator have to create a working project with a default database connection (sqlite is fine). All ORM have to embedded a `config/database.js` file with a default configuration. Another solution is to update tutorial quickly and tell the user how make it to work.

#### Environment
- node version: all
- trails version: 1.0.0-beta-10
- operating system: all

**Comment by jaumard** [comment]
Also here https://github.com/trailsjs/trails/blob/master/archetype/config/database.js#L31 the name is `sqlitedev` and here https://github.com/trailsjs/trails/blob/master/archetype/config/database.js#L39 `dev` is expected. For new user it can be disappointed

**Comment by tjwebb** [comment]
Sorry about that, I'm still working on the generators. I'll try to clear this up tonight.

**Comment by jaumard** [comment]
@tjwebb no problem :) I rename the `sqlitedev` to `dev` on this PR https://github.com/trailsjs/trails/pull/161

**Comment by jaumard** [comment]
Here is what I do for sequelize : 
- No defaultStore configured under `config.database`  
- Under `validate` method just log a warning if no store was found
- Ignore every models if no store configured

Like this user have a working project and are warn about an ORM problems

**Comment by jaumard** [comment]
Look like it doesn't crash anymore, closing
