### ISSUE TITLE
Freeze config for module unrequirable

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#180]
#### Issue Description
Module like `angular2` is not 'requirable' at all, in any js files you can't do require('angular2') or you have Cannot find module 'angular2'. It's another issue than this one but I put it here because it's related.

```
error: 
 Error: Cannot find module 'angular2'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/lib/trails.js:119:53
    at Array.find (native)
    at /Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/lib/trails.js:119:36
    at Array.forEach (native)
    at Object.freezeConfig (/Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/lib/trails.js:117:15)
    at TrailsApp.<anonymous> (/Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/lib/trails.js:169:59)
    at TrailsApp.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TrailsApp.emit (events.js:166:7)
    at TrailsApp.emit (/Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/index.js:142:23)
    at /Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/lib/trailpack.js:34:23
    at process._tickDomainCallback (node.js:407:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:134:18)
    at node.js:962:3
error: The application did not boot successfully.
```
#### Environment
- node version: all
- trails version: all since freeze 
- operating system: all

#### Possible fix 
Here https://github.com/trailsjs/trails/blob/master/lib/trails.js#L122 : 
```
const ignoreModule = modules.find(moduleId => {
        try {
          return require(moduleId) === prop
        } catch (err) {
          return false
        }
      })
```

**Comment by tjwebb** [comment]
Taking a look now.

**Comment by jaumard** [comment]
Look like it's fixed on the V1 :) thanks !
