### ISSUE TITLE
eslint cannot find module 'eslint-config-trails' on newly generated app

### ISSUE THREAD

**Issue by metzuda** [trailsjs/trails#241]
#### Issue Description
I noticed that eslint wasn't giving compatible output to my code editor, so I tried running the CLI; here's the output I get:

``` javascript
Cannot find module 'eslint-config-trails'
Referenced from: /Users/user1/server-trails/package.json
Error: Cannot find module 'eslint-config-trails'
Referenced from: /Users/user1/server-trails/package.json
    at Object.resolve (/usr/local/lib/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:478:33)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:495:26)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:256:22)
```

The module is installed:

```
$ ls node_modules/ | grep trails
eslint-config-trails
trails
trails-controller
trails-model
trails-policy
trails-service
```

Sorry if I'm missing something obvious 😟

#### Environment
- node version: 6.2.2
- trails version: 1.0.4
- operating system: macOS 10.12.1 Beta

**Comment by scott-wyatt** [comment]
I don't know if this will work for you, but for me, the problem was with xcode.  After upgrading to macOS I had to agree to some new permissions for xcode before linting worked for me. Perhaps that will help.

**Comment by jaumard** [comment]
You  can also try to remove node_modules folder and do a clean install `npm i`. But @scott-wyatt was right after an update xcode need to install some tools and need new permissions

**Comment by metzuda** [comment]
Thanks for your responses!

After some more fiddling around, I realised the problem: I was running eslint installed globally (which is required by my editor to use it); so using `eslint .` would invoke the *global* eslint; I had to install `eslint-config-trails` globally to make it work. It's very obvious in hindsight.
