### ISSUE TITLE
Add routes on env config

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#247]
#### Issue Description
I'm trying to add routes on testing env but after this trails doesn't start anymore (on tests).
I add : 
```
routes: [,
    {
      method: 'GET',
      path: '/api/v1',
      handler: 'DefaultController.test'
    }
  ],
```

Then the error is : 
```
2016-10-27T06:59:49.894Z - error: 
 TypeError: Cannot read property 'method' of undefined
    at Object.getRouteConflict (/Users/jaumard/LISAProjects/lisa-box/node_modules/trailpack-router/lib/util.js:171:44)
    at _.map.route (/Users/jaumard/LISAProjects/lisa-box/node_modules/trailpack-router/lib/util.js:192:26)
    at arrayMap (/Users/jaumard/LISAProjects/lisa-box/node_modules/lodash/lodash.js:645:23)
    at Function.map (/Users/jaumard/LISAProjects/lisa-box/node_modules/lodash/lodash.js:9505:14)
    at Object.findRouteConflicts (/Users/jaumard/LISAProjects/lisa-box/node_modules/trailpack-router/lib/util.js:189:25)
    at Object.validateRouteList (/Users/jaumard/LISAProjects/lisa-box/node_modules/trailpack-router/lib/validator.js:24:21)
    at Router.validate (/Users/jaumard/LISAProjects/lisa-box/node_modules/trailpack-router/index.js:23:21)
    at app.after.then (/Users/jaumard/LISAProjects/lisa-box/node_modules/trails/lib/trailpack.js:68:26)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

#### Environment
- node version: 6.8.1
- trails version: 1.0.4
- operating system: mac osX

**Comment by jaumard** [comment]
My bad :) just an extra comma that make all crash ^^
