### ISSUE TITLE
Trails app does not exit when trailpack initialization fails

### ISSUE THREAD

**Issue by swarthy** [trailsjs/trails#279]
#### Issue Description
Hi!
If trailpack throws error due initialization, app stops here https://github.com/trailsjs/trails/blob/master/lib/trailpack.js#L43, but process doesn't __exit__

#### Expected
After fail startup application will exit with some errorcode

#### Environment
- node version: 7.4.0
- trails version: 2.0.1
- operating system: Ubuntu 16.10

#### Example
trailpack-test/index.js
```javascript
'use strict'

const Trailpack = require('trailpack')
const Promise = require('bluebird')

module.exports = class TestTrailpack extends Trailpack {

  /**
   * TODO document method
   */
  validate () {

  }

  /**
   * TODO document method
   */
  configure () {

  }

  /**
   * TODO document method
   */
  initialize () {
    return Promise.reject(new Error('Test error'))
  }

  constructor (app) {
    super(app, {
      config: require('./config'),
      api: require('./api'),
      pkg: require('./package')
    })
  }
}
```

trailpack-test/test/app.js
```javascript
'use strict'

const _ = require('lodash')
const smokesignals = require('smokesignals')

module.exports = _.defaultsDeep({
  pkg: {
    name: require('../package').name + '-test'
  },
  api: {
    models: { },
    controllers: { },
    services: { }
  },
  config: {
    log: {
      logger: new smokesignals.Logger('silly')
    },
    main: {
      packs: [
        smokesignals.Trailpack,
        require('../')
      ]
    }
  }
}, smokesignals.FailsafeConfig)
```

trailpack-test/test/index.js
```javascript
const TrailsApp = require('trails')

before(function () {
  this.timeout(5000)
  global.app = new TrailsApp(require('./app'))
  return global.app.start()
  .catch(err => {
    console.error('Startup error:', err)
    return global.app.stop(err)
  })
})

after(function () {
  return global.app.stop()
})
```

npm test output
```bash
alex@alex-workstantion:~/work/trailpack-test$ npm test

> trailpack-test@0.0.0 test /home/alex/work/trailpack-test
> eslint . && mocha



smokesignal logger: [ debug ] trails event: trailpack:smokesignals:constructed
smokesignal logger: [ debug ] trails event: trailpack:test:constructed
smokesignal logger: [ debug ] trails event: trails:start
smokesignal logger: [ debug ] trailpack: validating smokesignals
smokesignal logger: [ debug ] trailpack: validating test
smokesignal logger: [ debug ] trails event: trailpack:smokesignals:validated
smokesignal logger: [ debug ] trails event: trailpack:test:validated
smokesignal logger: [ debug ] trails event: trailpack:all:validated
smokesignal logger: [ debug ] trailpack: configuring smokesignals
smokesignal logger: [ debug ] trailpack: configuring test
smokesignal logger: [ debug ] trails event: trailpack:smokesignals:configured
smokesignal logger: [ debug ] trails event: trailpack:test:configured
smokesignal logger: [ debug ] trails event: trailpack:all:configured
smokesignal logger: [ debug ] trailpack: initializing smokesignals
smokesignal logger: [ debug ] trailpack: initializing test
smokesignal logger: [ debug ] trails event: trailpack:smokesignals:initialized
smokesignal logger: [ error ] 
 Error: Test error
    at TestTrailpack.initialize (/home/alex/work/trailpack-test/index.js:26:27)
    at app.after.then.then (/home/alex/work/trailpack-test/node_modules/trails/lib/trailpack.js:42:26)
smokesignal logger: [ error ] The application did not boot successfully.
smokesignal logger: [ error ] Try increasing the loglevel to "debug" to learn more
smokesignal logger: [ debug ] trails event: trails:stop
smokesignal logger: [ silly ] 
      Happy trails to you, until we meet again.
      - Dale Evans
    
smokesignal logger: [ info ] Shutting down...
smokesignal logger: [ debug ] Unloading trailpack smokesignals ...
smokesignal logger: [ debug ] Unloading trailpack test ...
smokesignal logger: [ debug ] All trailpacks unloaded. Done.
smokesignal logger: [ debug ] trails event: trailpack:test:initialized
  1) "before all" hook
smokesignal logger: [ error ] The application did not boot successfully.
smokesignal logger: [ error ] Try increasing the loglevel to "debug" to learn more
smokesignal logger: [ debug ] trails event: trails:stop
smokesignal logger: [ debug ] Unloading trailpack smokesignals ...
smokesignal logger: [ debug ] Unloading trailpack test ...
smokesignal logger: [ debug ] All trailpacks unloaded. Done.

  0 passing (2s)
  1 failing

  1)  "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at Timeout.<anonymous> (/home/alex/work/trailpack-test/node_modules/mocha/lib/runnable.js:226:19)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)



npm ERR! Test failed.  See above for more details.
```

UPD: Sorry for disturb, was a long day (: all works as expected

**Comment by swarthy** [comment]
What I'm doing wrong (: ?
