### ISSUE TITLE
SSL Issue : while generating a new application

### ISSUE THREAD

**Issue by panbhatt** [trailsjs/trails#292]
#### Issue Description
SSL Issue while generating the application fresh from scratch. 

#### Environment
- node version:  V6.9.1, NPM (3.10.8)
- trails version:   Latest
- operating system: WINDOWS 7

Components selected: HAPI, MONGOOSE, FOOTPRINTS 

Commands Run: 
$ yo trails

Get ready to blaze a new Trails Application!

Checking for updates...
? Choose a Web Server hapi
? Choose an ORM mongoose
? Do you want to use Footprints (automatic REST API from models) ? Yes
? Module Name trails-1

RequestError: self signed certificate in certificate chain
    at ClientRequest.req.once.err (d:\PBHATT3\AppData\nvm\v6.9.1\node_modules\generator-trails\node_modules\npm-name\node_modules\got\index.js:73:21)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

events.js:160
      throw er; // Unhandled 'error' event
      ^
RequestError: self signed certificate in certificate chain
    at ClientRequest.req.once.err (d:\PBHATT3\AppData\nvm\v6.9.1\node_modules\generator-trails\node_modules\npm-name\node_modules\got\index.js:73:21)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by panbhatt** [comment]
Even setting SSL Config to false won't work. 
npm config set strict-ssl false

**Comment by tjwebb** [comment]
> RequestError: self signed certificate in certificate chain

Is it possible you're behind a corporate firewall/proxy of some sort? The trails generator just downloads directly from npm, so I don't know why you'd see SSL errors.

**Comment by tjwebb** [comment]
@panbhatt let know the latest status of your issue when you get a chance. Closing for now.

**Comment by panbhatt** [comment]
This issue seems to be working now when not behind the corporate firewall or proxy. 
however there r  a number of packages seems to be missing like trailpack-hapi , trailpack-mongoose, trail-pack-footprints. Once i do all npm install i recieve cannot find module ./controllers . 
npm starts seems to be having issues. 

> node server.js

module.js:471
    throw err;
    ^

Error: Cannot find module './controllers'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\ab\Learn\trails1\api\index.js:3:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\ab\Learn\trails1\index.js:5:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
