### ISSUE TITLE
Error: Cannot find module '../../../lib/util'

### ISSUE THREAD

**Issue by rayhaanq** [trailsjs/trails#310]
Hi there I'm trying to get a project up and running using trails but I can't seem to install it. I've done `npm install -g yo generator-trails` which works fine but when I do `yo trails` I get the error below. Any idea how this can be fixed?

#### Issue Description
```
Error: Cannot find module '../../../lib/util'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\SomePath\AppData\Roaming\npm\node_modules\generator-trails\generators\app\steps\writing.js:5:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

#### Environment
- node version: 8.9.1
- trails version: 2
- operating system: Windows 10

**Comment by rayhaanq** [comment]
The problem was probably because I didn't run npm install. I went to https://github.com/trailsjs/generator-trails and downloaded the zip of the repo, replaced my generator-trails files with the ones in the zip and ran npm install from that folder. Fixed for me.

**Comment by rayhaanq** [comment]
Now getting another error...

```
module.js:538
    throw err;
    ^

Error: Cannot find module 'trails/controller'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\SomePath\trails-test\node_modules\trailpack-express\lib\utils.js:3:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\SomePath\trails-test\node_modules\trailpack-express\lib\server.js:16:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rayhaan\AppData\Roaming\npm-cache\_logs\2017-11-25T11_27_25_359Z-debug.log
```

This generator is really broken.

**Comment by alient** [comment]
I'm getting the same error `Error: Cannot find module '../../../lib/util'` on Node 6 and Mac.

**Comment by rayhaanq** [comment]
@alient DId you try what I did?

**Comment by alient** [comment]
Too much work. Defeats the purpose. Moving to the next framework.  8-)

**Comment by scott-wyatt** [comment]
Hi all, trails is a bit between v3 and v2 atm which has been causing some issues with the generator in v3. If you are interested in starting fast, you'll want to stick with v2 as we get everything migrated over.  The migration from v3 to v2 appears to be pretty easy, but it's got some work needed before I'd recommend it.

**Comment by rayhaanq** [comment]
Hey Scott, how do we install a specific version of trails using yo?

**Comment by pixelbacon** [comment]
Same error... And not to throw a fit, but wasn't documentation not being updated a big issue with the big S?

I understand big version changes, but if the suggested method of getting started is the generator method... the generator method should always work, and the master branch should always match up with the generator. This makes me think it's going to be another endeavor of searching through github issues or stackoverflow to see what something broke and how to fix it...

**Comment by scott-wyatt** [comment]
@pixelbacon This is a good point.  @trailsjs/maintainers and doc writers, when making our docs and getting started, we should probably globally install the version of the generator we are using. `npm install -g yo generator-trails@2` and `npm install -g yo generator-trails@3` etc. so that when trails v4 comes out, we don't have this issue again.
