### ISSUE TITLE
V3 configuration trailpack-email

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#322]
#### Issue Description
The trailpack-email contain this configuration: 
```
const smtpTransport = require('nodemailer-smtp-transport')
const nodemailer = require('nodemailer')

const transport = nodemailer.createTransport(smtpTransport({
  service: 'gmail',
  auth: {
    user: 'jimmy.aumard@gmail.com',
    pass: 'blablabla'
  }
}))

/**
 * Email Configuration
 * (app.config.email)
 *
 * Configure email, smtp, auth
 *
 * @see {@link https://github.com/jaumard/trailpack-email}
 */
module.exports = {
  //Custom transporter object to send email
  customTransporter: transport,

  /*
   * Default data use with EmailService.send
   * from, to, css, bcc, subject, text, html, attachments
   */
  defaultData: {
    to: 'jimmy.aumard@gmail.com'
  }
}

```

The problem is apparently `customTransporter: transport` when trails is trying to flatten the config object, I get this error:

```
/usr/local/bin/node /Users/jaumard/TrailsProjects/jaumard.com/server.js
/Users/jaumard/TrailsProjects/jaumard.com/node_modules/trails/lib/Configuration.js:81
    Object.entries(tree).forEach(([k, v]) => {
                         ^

RangeError: Maximum call stack size exceeded
    at Array.forEach (<anonymous>)
    at Function.flattenTree (/Users/jaumard/TrailsProjects/jaumard.com/node_modules/trails/lib/Configuration.js:81:26)
    at Object.entries.forEach (/Users/jaumard/TrailsProjects/jaumard.com/node_modules/trails/lib/Configuration.js:83:42)
    at Array.forEach (<anonymous>)
    at Function.flattenTree (/Users/jaumard/TrailsProjects/jaumard.com/node_modules/trails/lib/Configuration.js:81:26)
    at Object.entries.forEach (/Users/jaumard/TrailsProjects/jaumard.com/node_modules/trails/lib/Configuration.js:83:42)
    at Array.forEach (<anonymous>)
    at Function.flattenTree (/Users/jaumard/TrailsProjects/jaumard.com/node_modules/trails/lib/Configuration.js:81:26)
    at Object.entries.forEach (/Users/jaumard/TrailsProjects/jaumard.com/node_modules/trails/lib/Configuration.js:83:42)
    at Array.forEach (<anonymous>)
    at Function.flattenTree (/Users/jaumard/TrailsProjects/jaumard.com/node_modules/trails/lib/Configuration.js:81:26)
    at Object.entries.forEach (/Users/jaumard/TrailsProjects/jaumard.com/node_modules/trails/lib/Configuration.js:83:42)
    at Array.forEach (<anonymous>)
    at Function.flattenTree (/Users/jaumard/TrailsProjects/jaumard.com/node_modules/trails/lib/Configuration.js:81:26)
    at Object.entries.forEach (/Users/jaumard/TrailsProjects/jaumard.com/node_modules/trails/lib/Configuration.js:83:42)
    at Array.forEach (<anonymous>)

Process finished with exit code 1
```

#### Environment
- node version: 8.9.4
- trails version: 3.2.1
- operating system: Mac

any idea @trailsjs/maintainers ?

**Comment by scott-wyatt** [comment]
Bummer, this would need to be refactored so that the transport configuration is consumed versus being set. It makes it less flexible, but more testable unfortunately.

**Comment by jaumard** [comment]
I don't think it's possible to just have the config here as there a lot of plugin for node mailer and I can't manage them all just by config... I didn't try yet to migrate trailpack-passport but maybe I'll have the same problem with strategies set under config :/

**Comment by jaumard** [comment]
A hack is to use a callback `customTransporter: () => transport` as it can't be flattened, then no more problems.
