### ISSUE TITLE
trails:stop event should be more forcing

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#48]
We don't really want any further events firing after `trails:stop` is emitted. 

```
debug: trails event: trails:start
verbose: Trailpacks: All Validated.
debug: trails event: trailpack:all:validated
debug: trails event: trailpack:core:configured
debug: trails event: trailpack:smokesignals:configured
debug: trails event: trailpack:repl:configured
debug: trails event: trailpack:router:configured
debug: trails event: trailpack:waterline:configured
debug: trails event: trailpack:all:configured
debug: trails event: trailpack:smokesignals:initialized
debug: trails event: trailpack:repl:initialized
debug: trails event: trailpack:router:initialized
error:
 TypeError: lib.i18n.loadLocales is not a function
    at Core.initialize (/Users/tjwebb/workspace/trails/trailpack-core/index.js:55:14)
    at /Users/tjwebb/workspace/trails/trails/lib/trailpack.js:46:26
    at process._tickDomainCallback (node.js:411:9)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
debug: trails event: trails:stop
debug: trails event: trailpack:waterline:initialized
```

**Comment by Alaneor** [comment]
I don't think this can be prevented unless the events are handed over to `EventEmitter` in current tick [here](https://github.com/trailsjs/trails/blob/master/index.js#L99).

I do not understand the comment there - was this done in order to fix of some specific issue?

**Comment by Alaneor** [comment]
Ah, related - #10.

**Comment by tjwebb** [comment]
yea, I've made some progress in removing the nextTick() requirement but I'm not completely comfortable yet without an integration test that proves it's fixed. Trails will start and function perfectly without it, but I've run into issues where errors are thrown but are buried somewhere mysterious. 

We'll definitely knock this out before 1.0

**Comment by Alaneor** [comment]
Would it make sense to remove the workaround and release it for broader testing while still in beta? If there's no clear indication as to why it's broken, perhaps someone will stumble upon the problem in a way that will reveal the root cause.

**Comment by tjwebb** [comment]
I think I've resolved this, per my previous comment, I just need to manufacture a way to test it. My team has two deadlines that converge tomorrow, so I'm looking forward to having more time available starting again next week.
