### ISSUE TITLE
Package missing, where and how to fix ?

### ISSUE THREAD

**Issue by muxahuk** [trailsjs/trails#53]
trying to start server
```
C:\Users\M7\trails-demo>npm start

> trails-demo@0.0.0 start C:\Users\M7\trails-demo
> node server.js

module.js:328
    throw err;
    ^

Error: Cannot find module './controllers'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\M7\trails-demo\api\index.js:1:85)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\M7\trails-demo\index.js:3:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\M7\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! trails-demo@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trails-demo@0.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the trails-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs trails-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls trails-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\M7\trails-demo\npm-debug.log
```
Trying to make controller
```
C:\Users\M7\trails-demo>yo trails:controller Main
module.js:328
    throw err;
    ^

Error: Cannot find module 'yeoman-generator/node_modules/path-exists'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\M7\AppData\Roaming\npm\node_modules\generator-trails\generators\app\util.js:13:46)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```
Who's side is these error ? yo or trails:controller ???
Reinstalling bouth of them didn't helped!..

**Comment by konstantinzolotarev** [comment]
@muxahuk could you please create a repo with current application. So we could debug and find problem ?

**Comment by muxahuk** [comment]
I'v run commands:
`npm install -g yo`
`npm install -g generator-trails`
// restarted cmd
`mkdir trails-demo`
`cd trails-demo`
`yo trails`
That's it.

Then i run commands and u can see output above.. Is it necessery to make a repo ?
I'v tryed again and now it's:
```
C:\Users\M7\trails-demo2>npm start

> trails-demo-2@0.0.0 start C:\Users\M7\trails-demo2
> node server.js

info: Starting...
debug: trails event: trails:start
verbose: Trailpacks: All Validated.
debug: trails event: trailpack:all:validated
debug: trails event: trailpack:repl:configured
debug: trails event: trailpack:router:configured
debug: trails event: trailpack:core:configured
debug: trails event: trailpack:hapi:configured
debug: trails event: trailpack:all:configured
debug: trails event: trailpack:repl:initialized
debug: trails event: trailpack:router:initialized
error:
 AssertionError: missing path
    at Module.require (module.js:352:3)
    at require (internal/module.js:12:17)
    at Object.registerViews (C:\Users\M7\trails-demo2\node_modules\trailpack-hapi\lib\server.js:28:15)
    at Hapi.initialize (C:\Users\M7\trails-demo2\node_modules\trailpack-hapi\index.js:37:16)
    at C:\Users\M7\trails-demo2\node_modules\trails\lib\trailpack.js:46:26
    at process._tickDomainCallback (node.js:425:9)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3
debug: trails event: trails:stop
error:
 TypeError: Cannot read property 'compatibilityAPI' of undefined
    at t.u.value (C:\Users\M7\trails-demo2\node_modules\i18next\bin\index.js:2:3238)
    at C:\Users\M7\trails-demo2\node_modules\trailpack-core\lib\i18n.js:6:15
    at Object.init (C:\Users\M7\trails-demo2\node_modules\trailpack-core\lib\i18n.js:5:12)
    at Core.initialize (C:\Users\M7\trails-demo2\node_modules\trailpack-core\index.js:34:21)
    at C:\Users\M7\trails-demo2\node_modules\trails\lib\trailpack.js:46:26
    at process._tickDomainCallback (node.js:425:9)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3
debug: trails event: trails:stop
```
and trying generate controller gives the same error:
```
C:\Users\M7\trails-demo2>yo trails:controller Main
module.js:328
    throw err;
    ^

Error: Cannot find module 'yeoman-generator/node_modules/path-exists'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\M7\AppData\Roaming\npm\node_modules\generator-trails\generators\app\util.js:13:46)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

Running under:
```
C:\Users\M7\trails-demo2>node -v
v5.3.0

C:\Users\M7\trails-demo2>npm -v
3.5.3
```
On Windows 10 x64

**Comment by konstantinzolotarev** [comment]
@muxahuk Seems that first isue was because of wrong generator. I have issue (controllers missing) if I'm using generator from my own fork.

For missing path we have an issue: #36 
For `TypeError: Cannot read property 'compatibilityAPI' of undefined` I've created a new issue: #54.

For generate controller: created trailsjs/generator-trails#18

Thank you !
I'll close this issue. Please feel free to discuss everything in new issues.
