### ISSUE TITLE
node 5.x compatibility?

### ISSUE THREAD

**Issue by kokujin** [trailsjs/trails#62]
At the moment, loads of complaints in the console during scaffolding

**Comment by jaumard** [comment]
Can you share your console output ?

**Comment by jacqueslareau** [comment]
Here is the ouput on a basic yeoman scaffold (selected Hapi server). Windows 10, node 5.3.0

```
C:\Users\Jacques Lareau\Documents\Programming\trails-test>npm start

> trails-test@0.0.0 start C:\Users\Jacques Lareau\Documents\Programming\trails-test
> node server.js

debug: trails event: trailpack:core:constructed
debug: trails event: trailpack:repl:constructed
debug: trails event: trailpack:router:constructed
debug: trails event: trailpack:hapi:constructed
debug: trails event: trails:start
info: Starting...
debug: trails event: trailpack:repl:validated
debug: trails event: trailpack:hapi:validated
debug: trails event: trailpack:core:validated
debug: trails event: trailpack:router:validated
debug: trails event: trailpack:all:validated
debug: trails event: trailpack:repl:configured
debug: trails event: trailpack:router:configured
debug: trails event: trailpack:core:configured
debug: trails event: trailpack:hapi:configured
debug: trails event: trailpack:all:configured
debug: trails event: trailpack:repl:initialized
debug: trails event: trailpack:router:initialized
error:
 AssertionError: missing path
    at Module.require (module.js:352:3)
    at require (internal/module.js:12:17)
    at Object.registerViews (C:\Users\Jacques Lareau\Documents\Programming\trails-test\node_modules\trailpack-hapi\lib\server.js:28:15)
    at Hapi.initialize (C:\Users\Jacques Lareau\Documents\Programming\trails-test\node_modules\trailpack-hapi\index.js:37:16)
    at C:\Users\Jacques Lareau\Documents\Programming\trails-test\node_modules\trails\lib\trailpack.js:43:26
    at process._tickDomainCallback (node.js:425:9)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3
debug: trails event: trails:stop
error:
 TypeError: Cannot read property 'compatibilityAPI' of undefined
    at t.u.value (C:\Users\Jacques Lareau\Documents\Programming\trails-test\node_modules\i18next\bin\index.js:2:3238)
    at C:\Users\Jacques Lareau\Documents\Programming\trails-test\node_modules\trailpack-core\lib\i18n.js:6:15
    at Object.init (C:\Users\Jacques Lareau\Documents\Programming\trails-test\node_modules\trailpack-core\lib\i18n.js:5:12)
    at Core.initialize (C:\Users\Jacques Lareau\Documents\Programming\trails-test\node_modules\trailpack-core\index.js:34:21)
    at C:\Users\Jacques Lareau\Documents\Programming\trails-test\node_modules\trails\lib\trailpack.js:43:26
    at process._tickDomainCallback (node.js:425:9)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3
debug: trails event: trails:stop
```

**Comment by kokujin** [comment]
I am using Elementary OS Freya( Ubuntu 14.04)
Node version 5.2.0

here is a snippet

````npm WARN installMany lodash was bundled with trails-test@0.0.0, but bundled package wasn't found in unpacked tree
npm WARN installMany rc was bundled with trails-test@0.0.0, but bundled package wasn't found in unpacked tree
npm WARN installMany trailpack-core was bundled with trails-test@0.0.0, but bundled package wasn't found in unpacked tree
npm WARN installMany trailpack-hapi was bundled with trails-test@0.0.0, but bundled package wasn't found in unpacked tree
npm WARN installMany trailpack-repl was bundled with trails-test@0.0.0, but bundled package wasn't found in unpacked tree
npm WARN installMany trailpack-router was bundled with trails-test@0.0.0, but bundled package wasn't found in unpacked tree
npm WARN installMany trails was bundled with trails-test@0.0.0, but bundled package wasn't found in unpacked tree
npm WARN installMany waterline-sqlite3 was bundled with trails-test@0.0.0, but bundled package wasn't found in unpacked tree
npm WARN installMany winston was bundled with trails-test@0.0.0, but bundled package wasn't found in unpacked tree
npm WARN engine hoek@3.0.4: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine joi@7.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine hapi@11.1.4: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine vision@4.0.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine joi@7.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine joi@7.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine boom@3.1.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine items@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine isemail@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine topo@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine hoek@3.0.4: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine isemail@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine topo@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine hoek@3.0.4: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine isemail@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine topo@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine hoek@3.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine items@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine topo@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine boom@3.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine joi@7.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine cryptiles@3.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine mimos@3.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine heavy@4.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine kilt@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine subtext@3.0.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine iron@3.0.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine statehood@3.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine catbox-memory@2.0.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine ammo@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine peekaboo@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine call@3.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine accept@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine shot@2.0.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine catbox@7.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine wreck@7.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine pez@2.0.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine content@3.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine isemail@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine nigel@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine b64@3.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN engine vise@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
````

**Comment by jaumard** [comment]
Warnings are because you're using node 0.12 not 5.2
`current: {"node":"0.12.9","npm":"2.14.9"}`

**Comment by kokujin** [comment]
I beg to differ, I am using, "n" (https://github.com/tj/n) to manage my node installations, this is my console version output:

````
╰─$ node -v
v5.2.0

````

n output:

````
   node/4.2.1
    node/5.0.0
  ο node/5.2.0
````

**Comment by tjwebb** [comment]
> wanted: {"node":">=4.0.0"}

@kokujin you have some configuration issue, because your own machine thinks you're using some version older than 0.12. I would double-check this.

**Comment by troy0820** [comment]
@kokujin Yeah, check the version in '/usr/local/bin/node -v` to see if it's outputting the correct version.  Also check your PATH `echo $PATH` to see if that's in there.  Also check `which node` you are using.  You could be installing binaries from node and never be using them. If you ever installed node from apt-get .... it would've installed it to /usr/bin

**Comment by kokujin** [comment]
Thanks @tjwebb and @troy0820 for helping, I still have problems though. My console output

````
─$ which node && /usr/local/bin/node -v && echo $PATH                     1 ↵
/usr/local/bin/node
v5.2.0
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
````
I will try clearing the npm cach und re-installing

**Comment by aclave1** [comment]
@kokujin  what's the status on this? what version of npm are you running?

**Comment by tjwebb** [comment]
@kokujin if you're still having issues, let us know. Closing for now.
