### ISSUE TITLE
Fresh install of trails fail

### ISSUE THREAD

**Issue by hussainanjar** [trailsjs/trails#67]
After doing `yo trails` and running command `npm start` I get following error

```shell
debug: trails event: trailpack:core:constructed
debug: trails event: trailpack:repl:constructed
debug: trails event: trailpack:router:constructed
debug: trails event: trailpack:hapi:constructed
debug: trails event: trails:start
info: Starting...
debug: trails event: trailpack:repl:validated
debug: trails event: trailpack:hapi:validated
debug: trails event: trailpack:core:validated
debug: trails event: trailpack:router:validated
debug: trails event: trailpack:all:validated
debug: trails event: trailpack:repl:configured
debug: trails event: trailpack:router:configured
debug: trails event: trailpack:core:configured
debug: trails event: trailpack:hapi:configured
debug: trails event: trailpack:all:configured
debug: trails event: trailpack:repl:initialized
debug: trails event: trailpack:router:initialized
error: 
 AssertionError: missing path
    at Module.require (module.js:352:3)
    at require (internal/module.js:12:17)
    at Object.registerViews (/Users/hussainanjar/workspace/personal/trailsjs/node_modules/trailpack-hapi/lib/server.js:28:15)
    at Hapi.initialize (/Users/hussainanjar/workspace/personal/trailsjs/node_modules/trailpack-hapi/index.js:37:16)
    at /Users/hussainanjar/workspace/personal/trailsjs/node_modules/trails/lib/trailpack.js:43:26
    at process._tickDomainCallback (node.js:425:9)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3
debug: trails event: trails:stop
error: 
 TypeError: Cannot read property 'compatibilityAPI' of undefined
    at t.u.value (/Users/hussainanjar/workspace/personal/trailsjs/node_modules/i18next/bin/index.js:2:3238)
    at /Users/hussainanjar/workspace/personal/trailsjs/node_modules/trailpack-core/lib/i18n.js:6:15
    at Object.init (/Users/hussainanjar/workspace/personal/trailsjs/node_modules/trailpack-core/lib/i18n.js:5:12)
    at Core.initialize (/Users/hussainanjar/workspace/personal/trailsjs/node_modules/trailpack-core/index.js:34:21)
    at /Users/hussainanjar/workspace/personal/trailsjs/node_modules/trails/lib/trailpack.js:43:26
    at process._tickDomainCallback (node.js:425:9)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3
debug: trails event: trails:stop
```

**Comment by jacqueslareau** [comment]
Already reported in #36 and #54.

**Comment by konstantinzolotarev** [comment]
@hussainanjar @jacqueslareau thank you ! Please use existing issues for all question.
