### ISSUE TITLE
Error starting Trails from fresh deployment

### ISSUE THREAD

**Issue by abusaidm** [trailsjs/trails#96]
Installed Trails on windows, and generated using hapi, no errors.
when running 'npm start' I am met with the following error:

Error: Invalid path: \api\v1\{model}
    at Object.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (c:\projects\node\trails\test-hapi\node_modules\hapi\node_modules\hoek\lib\index.js:732:11)
    at internals.Router.normalize.internals.Router.analyze (c:\projects\node\trails\test-hapi\node_modules\hapi\node_modules\call\lib\index.js:184:10)
    at new module.exports.internals.Route.options (c:\projects\node\trails\test-hapi\node_modules\hapi\lib\route.js:79:46)
....

**Comment by tjwebb** [comment]
@abusaidm are you able to provide more information about your issue?

**Comment by tjwebb** [comment]
Closing until more info is provided.
